version: "3.8"

services:
  
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    container_name: mern-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: mern-frontend
    depends_on:
      - backend